run:
  tests: false

linters:
  disable-all: false
  enable-all: true
  disable:
    - goerr113
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gofumpt
    - gomnd
    - lll
    - nakedret
    - nlreturn
    - wsl
